# In: .github/workflows/publish-to-pypi.yml

name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # --- THIS PERMISSIONS BLOCK IS THE FIX ---
    permissions:
      id-token: write # This is required for trusted publishing

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # The 'user' and 'password' fields are now removed.
      # The action will automatically use trusted publishing.
